# Generated by Django 3.2.8 on 2021-10-29 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Value must be between 0 and 10'), django.core.validators.MaxValueValidator(10, 'Value must be between 0 and 10')])),
            ],
        ),
    ]
